plugins {
    id 'com.android.application'
}

// Exclude Google AndroidX.
configurations.all {
    exclude group: 'androidx.appcompat', module: 'appcompat'
    exclude group: 'androidx.core', module: 'core'
}

android {
    compileSdk target_sdk

    defaultConfig {
        // Samsung Music Player package name
        applicationId "com.samsung.android.music"

        minSdk 23
        targetSdk target_sdk

        versionCode 100
        versionName "10.0.0"

        vectorDrawables.useSupportLibrary = true
        
        // Samsung Music Player specific config
        manifestPlaceholders = [
            appName: "Samsung Music Player"
        ]
    }

    buildFeatures {
        buildConfig true
        viewBinding false
        dataBinding false
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {

    implementation("io.github.oneuiproject.sesl:appcompat:$sesl_appcompat_version")
    implementation("io.github.oneuiproject.sesl:apppickerview:$sesl_apppickerview_version")
    implementation("io.github.oneuiproject.sesl:material:$sesl_material_version")
    implementation("io.github.oneuiproject.sesl:indexscroll:$sesl_indexscroll_version")
    implementation("io.github.oneuiproject.sesl:picker-basic:$sesl_picker_basic_version")
    implementation("io.github.oneuiproject.sesl:picker-color:$sesl_picker_color_version")
    implementation("io.github.oneuiproject.sesl:preference:$sesl_preference_version")
    implementation("io.github.oneuiproject.sesl:recyclerview:$sesl_recyclerview_version")
    implementation("io.github.oneuiproject.sesl:swiperefreshlayout:$sesl_swiperefreshlayout_version")

    implementation("androidx.constraintlayout:constraintlayout:$androidx_constraintlayout_version")

    implementation 'com.airbnb.android:lottie:5.2.0'
    implementation 'io.github.oneuiproject:icons:1.1.0'

    implementation project(path: ':lib')
    //implementation("io.github.oneuiproject:design:$lib_version")
}
